[package]
name = "sixshoot"
version = "0.1.0"
authors = ["felix bowman <felixgbowman@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.10.0"
glfw = "0.20.0"
image = "0.23.12"
nalgebra-glm = "0.3"
